import { describe, it, expect } from "vitest";
import { Chess } from "chess.js";

import fixture from "./maia3-smoke-fixture.json";
import {
  MOVE_VOCAB,
  MOVE_TO_INDEX,
  HISTORY,
  TOKEN_DIM,
  NUM_SQUARES,
  mirrorMove,
  tokensFromFen,
  tokensAfterMove,
  legalMoveIndices,
  moveFromIndex,
  assertManifestContract,
} from "./maia3-tokenizer.js";

// Golden parity: the JS tokenizer must reproduce, byte-for-byte, the `tokens` and
// `legal_indices` the Python Maia3Adapter produced in maia3-smoke-fixture.json
// (generated by scripts/gen_maia3_smoke_fixture.py). If square indexing, the
// black-to-move mirror frame, or the move vocabulary drift, these fail instead of
// silently feeding the model garbage.

describe("move vocabulary", () => {
  it("matches the model's policy dimension and is a bijection", () => {
    expect(MOVE_VOCAB.length).toBe(fixture.logits_move_dim); // 4352
    expect(MOVE_TO_INDEX.size).toBe(MOVE_VOCAB.length); // no duplicate uci
  });

  it("orders plain moves a1a1..h8h8 then white-frame promotions", () => {
    expect(MOVE_VOCAB[0]).toBe("a1a1");
    expect(MOVE_VOCAB[4095]).toBe("h8h8");
    expect(MOVE_VOCAB[4096]).toBe("a7a8q");
    expect(MOVE_VOCAB[4351]).toBe("h7h8n");
  });
});

describe("mirrorMove", () => {
  it("flips ranks vertically and keeps the promotion piece", () => {
    expect(mirrorMove("e2e4")).toBe("e7e5");
    expect(mirrorMove("a7a8q")).toBe("a2a1q");
  });
});

describe("tokenization parity vs Python fixture", () => {
  for (const c of fixture.cases) {
    it(`reproduces tokens for ${c.name}`, () => {
      const tokens = tokensFromFen(c.fen);
      expect(tokens.length).toBe(NUM_SQUARES * TOKEN_DIM);
      expect(tokens.length).toBe(c.tokens.length);
      expect(Array.from(tokens)).toEqual(c.tokens);
    });

    it(`reproduces legal_indices for ${c.name}`, () => {
      expect(legalMoveIndices(c.fen)).toEqual(c.legal_indices);
    });
  }
});

describe("index <-> move round-trip (the mirror frame)", () => {
  for (const c of fixture.cases) {
    it(`every legal index maps back to a legal move for ${c.name}`, () => {
      const board = new Chess(c.fen);
      const realLegal = new Set(
        board.moves({ verbose: true }).map((m) => m.from + m.to + (m.promotion || "")),
      );
      const mapped = c.legal_indices.map((i) => moveFromIndex(i, c.fen));
      // No index drops out, and the mapped set equals the board's real legal moves.
      expect(mapped.every((uci) => uci !== null)).toBe(true);
      expect(new Set(mapped)).toEqual(realLegal);
    });
  }

  it("returns null for an index that is illegal in the position", () => {
    // a1a1 (index 0) is never a legal move.
    expect(moveFromIndex(0, fixture.cases[0].fen)).toBe(null);
  });

  // Black-to-move promotions stress the mirror frame the hardest: a real e2e1q must
  // round-trip through the white-frame vocab entry e7e8q. The two fixture positions
  // don't promote, so verify the property self-consistently (no Python reference
  // needed): the mapped legal set equals the board's real legal moves AND contains a
  // promotion. Black pawn on e2, Black to move.
  it("round-trips black-to-move promotions through the white vocab frame", () => {
    const promoFen = "8/8/8/8/8/7k/4p3/7K b - - 0 1";
    const board = new Chess(promoFen);
    const realLegal = new Set(
      board.moves({ verbose: true }).map((m) => m.from + m.to + (m.promotion || "")),
    );
    expect([...realLegal].some((uci) => uci === "e2e1q")).toBe(true);

    const indices = legalMoveIndices(promoFen);
    const mapped = indices.map((i) => moveFromIndex(i, promoFen));
    expect(mapped.every((uci) => uci !== null)).toBe(true);
    expect(new Set(mapped)).toEqual(realLegal);

    // The promotion lives in the vocab under its mirrored (white-frame) name.
    expect(MOVE_TO_INDEX.get(mirrorMove("e2e1q"))).toBe(MOVE_TO_INDEX.get("e7e8q"));
  });
});

describe("after-move tokens (value-head path)", () => {
  it("tokenizes the resulting position and rejects illegal moves", () => {
    const startFen = fixture.cases[0].fen;
    const afterE4 = tokensAfterMove(startFen, "e2e4");
    expect(afterE4).not.toBe(null);
    expect(afterE4.length).toBe(NUM_SQUARES * TOKEN_DIM);

    // After 1.e4 it's Black to move; the position differs from the start tokens.
    const start = tokensFromFen(startFen);
    expect(Array.from(afterE4)).not.toEqual(Array.from(start));

    // The after-move tokens must equal tokenizing the resulting FEN directly.
    const board = new Chess(startFen);
    board.move({ from: "e2", to: "e4" });
    expect(Array.from(afterE4)).toEqual(Array.from(tokensFromFen(board.fen())));

    expect(tokensAfterMove(startFen, "e2e5")).toBe(null); // illegal
  });
});

// assertManifestContract() is the fail-fast gate the provider/worker calls before
// trusting any token shape or legal mask: if a CDN artifact or a hand-edited manifest
// bumps the model's layout (history / token_dim / time-info / policy dim) past the
// tokenizer's hardwired constants, it must throw — NOT silently emit wrong-shape
// tokens. The smoke fixture only exercises the happy path, so these negative tests
// pin every field's drift, guarding against a future edit that loosens a check or
// reorders the message and quietly defeats the gate.
describe("assertManifestContract (fail-fast layout gate)", () => {
  // A manifest that matches the tokenizer's hardwired contract exactly. Derived from
  // the tokenizer's own exported constants so the baseline can't drift away from what
  // the gate checks against. Each test perturbs ONE field.
  const validManifest = () => ({
    history: HISTORY,
    token_dim: TOKEN_DIM,
    include_time_info: false,
    io: { logits_move_dim: MOVE_VOCAB.length },
  });

  it("passes for a manifest matching the contract", () => {
    expect(() => assertManifestContract(validManifest())).not.toThrow();
  });

  it("throws when history drifts", () => {
    const m = validManifest();
    m.history = HISTORY + 1;
    expect(() => assertManifestContract(m)).toThrow(/history/);
  });

  it("throws when token_dim drifts", () => {
    const m = validManifest();
    m.token_dim = TOKEN_DIM - 1;
    expect(() => assertManifestContract(m)).toThrow(/token_dim/);
  });

  it("throws when include_time_info is enabled (time info unsupported)", () => {
    const m = validManifest();
    m.include_time_info = true;
    expect(() => assertManifestContract(m)).toThrow(/include_time_info/);
  });

  it("throws when the policy dimension drifts", () => {
    const m = validManifest();
    m.io = { logits_move_dim: MOVE_VOCAB.length - 1 };
    expect(() => assertManifestContract(m)).toThrow(/logits_move_dim/);
  });

  it("throws on an empty manifest (no field silently defaults to OK)", () => {
    expect(() => assertManifestContract({})).toThrow();
  });

  it("reports every drifting field at once (no early-return hides later drift)", () => {
    let err;
    try {
      assertManifestContract({
        history: 1,
        token_dim: 1,
        include_time_info: true,
        io: { logits_move_dim: 1 },
      });
    } catch (e) {
      err = e;
    }
    expect(err).toBeTruthy();
    expect(err.message).toMatch(/history/);
    expect(err.message).toMatch(/token_dim/);
    expect(err.message).toMatch(/include_time_info/);
    expect(err.message).toMatch(/logits_move_dim/);
  });
});
