"""repertoires team_id + visibility (sharing)

Revision ID: 2bf1a51905b1
Revises: f6818a5e1449
Create Date: 2026-06-08 17:44:04.650185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf1a51905b1'
down_revision: Union[str, Sequence[str], None] = 'f6818a5e1449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No DB-level FK to teams (see sa_tables): referential integrity for sharing is
    # enforced in app logic; a dangling team_id fails closed in the read gate.
    with op.batch_alter_table('repertoires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Text(), nullable=True))
        batch_op.create_index('idx_repertoires_team', ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repertoires', schema=None) as batch_op:
        batch_op.drop_index('idx_repertoires_team')
        batch_op.drop_column('visibility')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
