"""legacy domain tables baseline

Revision ID: 9fc171c00d10
Revises: bbed25d490b5
Create Date: 2026-06-07 15:37:08.134269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc171c00d10'
down_revision: Union[str, Sequence[str], None] = 'bbed25d490b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('engine_evaluations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('nodes', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('score_cp', sa.Integer(), nullable=True),
    sa.Column('mate_in', sa.Integer(), nullable=True),
    sa.Column('best_move_uci', sa.Text(), nullable=True),
    sa.Column('pv_json', sa.Text(), nullable=False),
    sa.Column('wdl_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fen', 'engine', 'depth', 'nodes', 'time_ms')
    )
    op.create_table('engine_settings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('engine_name', sa.Text(), nullable=False),
    sa.Column('executable_path', sa.Text(), nullable=True),
    sa.Column('default_depth', sa.Integer(), nullable=True),
    sa.Column('default_nodes', sa.Integer(), nullable=True),
    sa.Column('default_time_ms', sa.Integer(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('initial_fen', sa.Text(), nullable=False),
    sa.Column('white', sa.Text(), nullable=True),
    sa.Column('black', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('played_at', sa.Text(), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=True),
    sa.Column('lichess_id', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('idx_games_owner', ['owner_user_id'], unique=False)
        batch_op.create_index('idx_games_owner_lichess', ['owner_user_id', 'lichess_id'], unique=True)

    op.create_table('lichess_imports',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('imported_game_ids_json', sa.Text(), nullable=False),
    sa.Column('skipped_game_ids_json', sa.Text(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maia_predictions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('move_uci', sa.Text(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('rating_bucket', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fen', 'move_uci', 'model', 'rating_bucket')
    )
    with op.batch_alter_table('maia_predictions', schema=None) as batch_op:
        batch_op.create_index('idx_maia_predictions_fen', ['fen'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('side_to_move', sa.Text(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('halfmove_clock', sa.Integer(), nullable=False),
    sa.Column('fullmove_number', sa.Integer(), nullable=False),
    sa.Column('legal_moves_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fen')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('lichess_username', sa.Text(), nullable=True),
    sa.Column('preferred_engine', sa.Text(), nullable=False),
    sa.Column('default_analysis_depth', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.Text(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('critical_ply_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('game_id', sa.Text(), nullable=True),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('side_to_move', sa.Text(), nullable=False),
    sa.Column('uci', sa.Text(), nullable=False),
    sa.Column('san', sa.Text(), nullable=False),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('fen_after', sa.Text(), nullable=False),
    sa.Column('engine_eval_before_id', sa.Text(), nullable=True),
    sa.Column('engine_eval_after_id', sa.Text(), nullable=True),
    sa.Column('best_move_uci', sa.Text(), nullable=True),
    sa.Column('best_move_eval_id', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['best_move_eval_id'], ['engine_evaluations.id'], ),
    sa.ForeignKeyConstraint(['engine_eval_after_id'], ['engine_evaluations.id'], ),
    sa.ForeignKeyConstraint(['engine_eval_before_id'], ['engine_evaluations.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.create_index('idx_moves_fen_before', ['fen_before'], unique=False)
        batch_op.create_index('idx_moves_game_ply', ['game_id', 'ply'], unique=False)
        batch_op.create_index('idx_moves_uci', ['uci'], unique=False)

    op.create_table('repertoires',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_profile_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('root_fen', sa.Text(), nullable=False),
    sa.Column('root_node_id', sa.Text(), nullable=True),
    sa.Column('main_engine', sa.Text(), nullable=False),
    sa.Column('human_model', sa.Text(), nullable=False),
    sa.Column('branch_depth', sa.Integer(), nullable=False),
    sa.Column('opponent_branch_threshold', sa.Float(), nullable=False),
    sa.Column('sub_branch_threshold', sa.Float(), nullable=False),
    sa.Column('max_total_nodes', sa.Integer(), nullable=False),
    sa.Column('max_line_length', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repertoires', schema=None) as batch_op:
        batch_op.create_index('idx_repertoires_owner', ['user_profile_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_profile_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_user_sessions_profile', ['user_profile_id'], unique=False)

    op.create_table('opening_lines',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repertoire_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('node_ids_json', sa.Text(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opening_nodes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repertoire_id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('move_id', sa.Text(), nullable=True),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('side_to_move', sa.Text(), nullable=False),
    sa.Column('engine_evaluation_id', sa.Text(), nullable=True),
    sa.Column('maia_probability', sa.Float(), nullable=True),
    sa.Column('is_mainline', sa.Integer(), nullable=False),
    sa.Column('is_user_prepared_move', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('arrows_json', sa.Text(), nullable=False),
    sa.Column('circles_json', sa.Text(), nullable=False),
    sa.Column('tactical_warning', sa.Text(), nullable=True),
    sa.Column('strategic_idea', sa.Text(), nullable=True),
    sa.Column('typical_plan', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['engine_evaluation_id'], ['engine_evaluations.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['opening_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opening_nodes', schema=None) as batch_op:
        batch_op.create_index('idx_opening_nodes_fen', ['fen'], unique=False)
        batch_op.create_index('idx_opening_nodes_repertoire_parent', ['repertoire_id', 'parent_id'], unique=False)

    op.create_table('generation_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repertoire_id', sa.Text(), nullable=False),
    sa.Column('root_node_id', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('undo_log_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_node_id'], ['opening_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practical_opening_matches',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('game_id', sa.Text(), nullable=False),
    sa.Column('user_color', sa.Text(), nullable=False),
    sa.Column('repertoire_id', sa.Text(), nullable=True),
    sa.Column('matched_plies', sa.Integer(), nullable=False),
    sa.Column('last_matched_node_id', sa.Text(), nullable=True),
    sa.Column('departure_ply', sa.Integer(), nullable=True),
    sa.Column('departure_move_uci', sa.Text(), nullable=True),
    sa.Column('departure_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_matched_node_id'], ['opening_nodes.id'], ),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_progress',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_profile_id', sa.Text(), nullable=True),
    sa.Column('repertoire_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.Text(), nullable=True),
    sa.Column('spaced_repetition_score', sa.Float(), nullable=False),
    sa.Column('due_at', sa.Text(), nullable=True),
    sa.Column('is_mastered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['opening_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_profile_id', 'repertoire_id', 'node_id')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('repertoire_id', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('line_order_json', sa.Text(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Text(), nullable=True),
    sa.Column('mistakes_json', sa.Text(), nullable=False),
    sa.Column('mastered_nodes_json', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['current_node_id'], ['opening_nodes.id'], ),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_mistakes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('repertoire_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=False),
    sa.Column('expected_uci', sa.Text(), nullable=False),
    sa.Column('played_uci', sa.Text(), nullable=False),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['opening_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_mistakes')
    op.drop_table('training_sessions')
    op.drop_table('training_progress')
    op.drop_table('practical_opening_matches')
    op.drop_table('generation_runs')
    with op.batch_alter_table('opening_nodes', schema=None) as batch_op:
        batch_op.drop_index('idx_opening_nodes_repertoire_parent')
        batch_op.drop_index('idx_opening_nodes_fen')

    op.drop_table('opening_nodes')
    op.drop_table('opening_lines')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_sessions_profile')

    op.drop_table('user_sessions')
    with op.batch_alter_table('repertoires', schema=None) as batch_op:
        batch_op.drop_index('idx_repertoires_owner')

    op.drop_table('repertoires')
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_index('idx_moves_uci')
        batch_op.drop_index('idx_moves_game_ply')
        batch_op.drop_index('idx_moves_fen_before')

    op.drop_table('moves')
    op.drop_table('analysis_results')
    op.drop_table('user_profiles')
    op.drop_table('positions')
    with op.batch_alter_table('maia_predictions', schema=None) as batch_op:
        batch_op.drop_index('idx_maia_predictions_fen')

    op.drop_table('maia_predictions')
    op.drop_table('lichess_imports')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('idx_games_owner_lichess')
        batch_op.drop_index('idx_games_owner')

    op.drop_table('games')
    op.drop_table('engine_settings')
    op.drop_table('engine_evaluations')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
