"""Generate browser constants from their Python owners. Run with Python 3.11+."""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from prepforge_chess.core.limits import MAX_FETCH, MAX_PLAN_CHANGES
from prepforge_chess.services.classification import CP_CLAMP, WC_SIGMOID_SCALE, ClassificationConfig
from prepforge_chess.services.brilliant import BrilliantConfig
from prepforge_chess.services.opening_builder import MAINLINE_THRESHOLD
from prepforge_chess.services.scheduler import DEFAULT_NEW_CAP

OUTPUT = ROOT / "web-src/generated/shared-constants.js"


def render() -> str:
    classification = ClassificationConfig()
    brilliant = BrilliantConfig()
    constants = {
        "CP_CLAMP": CP_CLAMP,
        "WC_SIGMOID_SCALE": WC_SIGMOID_SCALE,
        "EXCELLENT_MAX_LOSS": classification.excellent_loss * 100,
        "GOOD_MAX_LOSS": classification.good_loss * 100,
        "INACCURACY_MAX_LOSS": classification.inaccuracy_loss * 100,
        "MISTAKE_MAX_LOSS": classification.mistake_loss * 100,
        "BRILLIANT_MAX_CANDIDATE_WIN_DELTA": classification.excellent_loss * 100,
        "BRILLIANT_MAX_HUMAN_PROB": brilliant.max_human_probability,
        "BRILLIANT_MIN_WIN_GAP": brilliant.min_reveal_score * 100,
        "BRILLIANT_MIN_TRAP_GAP": brilliant.min_trap_gap,
        "BRILLIANT_MIN_ONLY_MOVE_GAP": brilliant.min_only_move_gap * 100,
        "BRILLIANT_MIN_SACRIFICE": brilliant.min_sacrifice,
        "GREAT_MAX_HUMAN_PROB": brilliant.great_max_human_probability,
        "GREAT_MIN_TRAP_GAP": brilliant.great_min_trap_gap,
        "GREAT_MIN_TWO_MOVE_GAP": brilliant.great_min_two_move_gap * 100,
        "GREAT_MIN_WIN": brilliant.great_min_win * 100,
        "GREAT_MAX_WIN_BEFORE": brilliant.great_max_win_before * 100,
        "MAX_PLAN_CHANGES": MAX_PLAN_CHANGES,
        "MAX_FETCH": MAX_FETCH,
        "MAINLINE_THRESHOLD": MAINLINE_THRESHOLD,
        "SMART_NEW_CAP": DEFAULT_NEW_CAP,
    }
    return "// Generated by scripts/gen_shared_constants.py; do not edit.\n" + "".join(
        f"export const {name} = {json.dumps(value)};\n" for name, value in constants.items()
    )


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")
